### ISSUE TITLE
New switcher device won't get state 

### ISSUE THREAD

**Issue by adizag** [TomerFi/switcher_webapi#665]
### What happened?

New Switcher touch (V3) device arrived with FW 5.10 installed.

I extracted the device info using the discover_devices.py script:
![image](https://github.com/TomerFi/switcher_webapi/assets/17390016/7341d553-108e-4616-b1f9-12373eee67a4)

trying to get its state I get the following error:  `Get state request was not successful`

![d17c1e19-3a13-4d2e-b3d4-2f3ee934bf4a](https://github.com/TomerFi/switcher_webapi/assets/17390016/c6a74955-b937-4cf9-8fe4-ae8ab86b91bb)

Please notice the device ID, it looks strange, usually there are numbers with letters but I got only numbers.

Thanks @dmatik for assisting and getting @TomerFi involved!

### Module Version

1.2.4

### Device Type

Switcher Touch (V3)

### Firmware Version

5.10

### Relevant log output

```shell
2023-05-17 18:01:55,584 - aiohttp.server - INFO - starting server
2023-05-17 18:01:59,024 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:02:29,064 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:02:59,003 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:03:29,042 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:03:58,985 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:04:00,913 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:04:29,052 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:04:59,022 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:05:29,062 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:05:59,005 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
2023-05-17 18:06:29,043 - aiohttp.server - ERROR - caught exception while handing over to endpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 369, in get_state
    response = SwitcherStateResponse(state_resp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 200, in __post_init__
    self.state = parser.get_state()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/messages.py", line 85, in get_state
    return states[hex_state]
           ~~~~~~^^^^^^^^^^^
      
KeyError: ''
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/switcher_webapi/webapp.py", line 273, in error_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/switcher_webapi/webapp.py", line 103, in get_state
    return web.json_response(_serialize_object(await swapi.get_state()))
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 373, in get_state
    raise RuntimeError("get state request was not successful") from ve
RuntimeError: get state request was not successful
```

**Comment by adizag** [comment]
@TomerFi hi, any news?

**Comment by TomerFi** [comment]
No. Unfortunately not yet. I don't really have an environment for testing this.

**Comment by adizag** [comment]
ן can donate mine.
I can give you access to whatever you need.
Let me help you help me :)

____________________________________________
"יש המטביעים את צרותיהם - ויש המלמדים אותן לשחות..."
"אין מקום שהוא רחוק מדי"


‫בתאריך יום ב׳, 29 במאי 2023 ב-7:40 מאת ‪Tomer Figenblat‬‏ <‪
***@***.***‬‏>:‬
