### ISSUE TITLE
Failing on v1.2.5

### ISSUE THREAD

**Issue by dmatik** [TomerFi/switcher_webapi#707]
### What happened?

After updating to v1.2.5 the GET is failing.
Please see attached logs.
Returning back to v1.2.4 resolves the issue.

Request:
http://10.0.0.30:8150/switcher/get_state?id=07db64&ip=10.0.0.4

Compose:

>     switcher_webapi:
>         image: tomerfi/switcher_webapi:latest
>         container_name: switcher_webapi
>         hostname: switcher_webapi
>         restart: always
>         network_mode: bridge
>         ports:
>           - 8150:8000
>         environment:
>             TZ: "Asia/Jerusalem"
>             LOG_LEVEL: "DEBUG"

### Module Version

1.2.5

### Device Type

Switcher Touch (V3)

### Firmware Version

3.22

### Relevant log output

```shell
2024-01-13T08:26:08.822620062Z 2024-01-13 10:26:08,822 - aiohttp.server - INFO - starting server
2024-01-13T08:26:29.341924959Z 2024-01-13 10:26:29,339 - aiohttp.server - ERROR - caught exception while handing over to endpoint
2024-01-13T08:26:29.342546587Z Traceback (most recent call last):
2024-01-13T08:26:29.342642518Z   File "/usr/switcher_webapi/webapp.py", line 352, in error_middleware
2024-01-13T08:26:29.342702231Z     return await handler(request)
2024-01-13T08:26:29.342756817Z            ^^^^^^^^^^^^^^^^^^^^^^
2024-01-13T08:26:29.342807147Z   File "/usr/switcher_webapi/webapp.py", line 110, in get_state
2024-01-13T08:26:29.342859999Z     return web.json_response(_serialize_object(await swapi.get_state()))
2024-01-13T08:26:29.342912568Z                                                ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-13T08:26:29.342960984Z   File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 379, in get_state
2024-01-13T08:26:29.343024340Z     raise RuntimeError("login request was not successful")
2024-01-13T08:26:29.343079347Z RuntimeError: login request was not successful
2024-01-13T08:26:29.344101305Z 2024-01-13 10:26:29,343 - aiohttp.access - DEBUG - 10.0.0.30 GET /switcher/get_state done in 6.0560496670077555s: 500
2024-01-13T08:26:59.362775414Z 2024-01-13 10:26:59,357 - aiohttp.server - ERROR - caught exception while handing over to endpoint
2024-01-13T08:26:59.363647428Z Traceback (most recent call last):
2024-01-13T08:26:59.363780629Z   File "/usr/switcher_webapi/webapp.py", line 352, in error_middleware
2024-01-13T08:26:59.363853000Z     return await handler(request)
2024-01-13T08:26:59.363906197Z            ^^^^^^^^^^^^^^^^^^^^^^
2024-01-13T08:26:59.363956310Z   File "/usr/switcher_webapi/webapp.py", line 110, in get_state
2024-01-13T08:26:59.364016368Z     return web.json_response(_serialize_object(await swapi.get_state()))
2024-01-13T08:26:59.364170535Z                                                ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-13T08:26:59.364237461Z   File "/usr/local/lib/python3.11/site-packages/aioswitcher/api/__init__.py", line 379, in get_state
2024-01-13T08:26:59.364308973Z     raise RuntimeError("login request was not successful")
2024-01-13T08:26:59.364383955Z RuntimeError: login request was not successful
2024-01-13T08:26:59.364435355Z 2024-01-13 10:26:59,359 - aiohttp.access - DEBUG - 10.0.0.30 GET /switcher/get_state done in 6.068148754944559s: 500
```

**Comment by TomerFi** [comment]
@YogevBokobza This happens with the new aioswithcer 3.4.1 bump. Does anything in the logs ring a bell?

**Comment by YogevBokobza** [comment]
@TomerFi Checking that I will update

**Comment by YogevBokobza** [comment]
@dmatik @TomerFi 
It was a stupid mistake by mine.
Fixed in https://github.com/TomerFi/switcher_webapi/pull/708
I also added dev env support so I can debug this git if needed.

**Comment by TomerFi** [comment]
[1.2.6](https://github.com/TomerFi/switcher_webapi/releases/tag/1.2.6)
